### ISSUE TITLE
Corrupt records

### ISSUE THREAD

**Issue by imduffy15** [spredfast/kafka-connect-s3#20]
Hi All,

I've been using this with the following configuration:

sink:

```
{
  "connector.class": "com.spredfast.kafka.connect.s3.sink.S3SinkConnector",
  "s3.endpoint": "https://s3-eu-central-1.amazonaws.com",
  "format.include.keys": "true",
  "topics": "da-b-content",
  "tasks.max": "1",
  "format": "binary",
  "name": "da-b-content-backup-25-july-5",
  "s3.bucket": "kafka-backups-dev",
  "value.converter": "com.spredfast.kafka.connect.s3.AlreadyBytesConverter",
  "local.buffer.dir": "/tmp",
  "s3.prefix": "da-b-content-5",
  "key.converter": "com.spredfast.kafka.connect.s3.AlreadyBytesConverter"
}
```

source:

```
{
  "connector.class": "com.spredfast.kafka.connect.s3.source.S3SourceConnector",
  "s3.endpoint": "https://s3-eu-central-1.amazonaws.com",
  "format.include.keys": "true",
  "tasks.max": "1",
  "topics": "da-b-content",
  "format": "binary",
  "name": "da-b-content-restore-5",
  "s3.bucket": "kafka-backups-dev",
  "value.converter": "com.spredfast.kafka.connect.s3.AlreadyBytesConverter",
  "s3.prefix": "da-b-content-5",
  "key.converter": "com.spredfast.kafka.connect.s3.AlreadyBytesConverter"
}
```

My source keeps dying due to some sort of record corruption:

```
org.apache.kafka.connect.errors.DataException: Corrupt record at da-b-content-25:2193805
	at com.spredfast.kafka.connect.s3.BytesRecordReader.die(BytesRecordReader.java:93)
	at com.spredfast.kafka.connect.s3.BytesRecordReader.readLen(BytesRecordReader.java:86)
	at com.spredfast.kafka.connect.s3.BytesRecordReader.readValueLen(BytesRecordReader.java:60)
	at com.spredfast.kafka.connect.s3.BytesRecordReader.read(BytesRecordReader.java:44)
	at com.spredfast.kafka.connect.s3.RecordReader$1.hasNext(RecordReader.java:34)
	at com.spredfast.kafka.connect.s3.source.S3FilesReader$1.hasNext(S3FilesReader.java:265)
	at com.spredfast.kafka.connect.s3.source.S3SourceTask.getSourceRecords(S3SourceTask.java:180)
	at com.spredfast.kafka.connect.s3.source.S3SourceTask.poll(S3SourceTask.java:153)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:162)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

Any ideas or workarounds for fixing this?

https://issues.apache.org/jira/browse/KAFKA-5211 looks potentially related, its fixed in 0.11.0.0 but confluent have yet to package up a 0.11.0.0 release of kafka-connect.

**Comment by pradeepcheers** [comment]
I have added the following properties in the source connector config. Try adding them to your source. I'm not sure if it fixes the issue.
`		"max.poll.records": "1000",
		"s3.page.size": "100",
		"max.partition.count": "200",
		"s3.start.marker": "2017-07-25"`
